services:
  api:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/app
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  migrate:
    build: .
    command: python db/pg.py
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}